version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: simple_todo_list
    ports:
      - "3307:3306"  # 修改为主机端口为3307，避免与本地MySQL冲突
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back-end/src/main/resources/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - todo-network

  # 后端服务
  backend:
    build: ./back-end
    container_name: todo-backend
    environment:
      stdl.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
      stdl.datasource.host: "mysql"
      stdl.datasource.port: "3306"
      stdl.datasource.database: "simple_todo_list"
      stdl.datasource.username: "root"
      stdl.datasource.password: "12345678"
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    networks:
      - todo-network

  # 前端服务
  frontend:
    build: ./front-end
    container_name: todo-frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8088  # 设置后端服务URL
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge